dist: precise

language: node_js
node_js:
  - "node"
  - 6
  - 7
  - 8

install: true
before_script:
  - npm i -g yarn
  - yarn global add npm-check-updates

script:
  - export ROOT=$PWD
  - >
    for path in 04-webpack-handlebars-bootswatch \
                03-webpack-pwa-handlebars-2 \
                03-webpack-pwa-handlebars-1 \
                02-service-worker \
                01-manifest \
                0-template; do

      export TARGET="$ROOT/$path"
      cd $TARGET

      yarn -i
      yarn predeploy
      yarn postdeploy
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi

      ncu
      ncu -u
      yarn -i
      yarn upgrade
      if [ -f npm-debug.log ]; then cat npm-debug.log; fi

    done;

cache:
  directories:
    - node_modules
    - $HOME/.npm
